---
- name: Install Kubernetes Master
  hosts: localhost
  become: true
  tasks:
    - name: Copy the script
      copy: src=/home/ubuntu/devopscapstoneproject1/install-kubernetes-master.sh dest=/tmp
    - name: Run the script
      command: sh /tmp/install-kubernetes-master.sh